repos:
-   repo: https://github.com/python-poetry/poetry
    rev: 2.1.1
    hooks:
    -   id: poetry-install
    -   id: poetry-check
    -   id: poetry-lock

-   repo: https://github.com/pycqa/flake8
    rev: 7.1.0
    hooks:
    -   id: flake8
        args: ['--extend-ignore=E203,E701', '--max-line-length=88']
        files: ^(src/unittest_scenarios|tests)/

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
    -   id: pyupgrade
        args: ['--py312-plus']

-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.1.0
    hooks:
    -   id: black
        language_version: python3.13
